### ISSUE TITLE
Add all MCQ settings from Coding Rooms

### ISSUE THREAD

**Issue by juicemind-dev** [JuiceMind/JuiceMind#150]

**Comment by guido-ferraro** [comment]
Options from editor:
> Make Poll
> Shuffle Options
> Allow Multiple Selections 
> Instant Feedback 
>Partial Credit 
> Ignore Hide Grades

Exported JSON:
```{
  "commonState": {
    "apiVersion": 1,
    "blockId": "290b1428-d230-4261-bd19-c6b7f66d3873",
    "createdAt": "0001-01-01T00:00:00Z",
    "creatorId": "",
    "id": "6e3712e5-0897-48f5-908e-3634bae19bed",
    "state": {
      "mode": 4,
      "prompt": {
        "text": "mcq test 2"
      },
      "selectionOptions": [
       ...
      ],
      "shuffle": true
    },
    "stateVersion": 6,
    "updatedAt": "0001-01-01T00:00:00Z"
  },
  "graderState": {
    "apiVersion": 1,
    "blockId": "290b1428-d230-4261-bd19-c6b7f66d3873",
    "createdAt": "0001-01-01T00:00:00Z",
    "creatorId": "",
    "id": "9c3847fd-8dd5-4e16-b8d3-66d3a028ba39",
    "state": {
      "options": {
        "partialCredit": true
      },
      "selectionIds": []
    },
    "stateVersion": 3,
    "updatedAt": "0001-01-01T00:00:00Z"
  },
  "points": 111
}
```

Mapping and notes:
1. `Make Poll` -> `makePoll`
2. `Shuffle Options` -> `shuffle`
3. `Allow Multiple Selections` -> `allowMultipleAnswers` (already coded). The expected behaviour based on CodingRooms observations is as follows:
3.1. If there's at least one correct choice in selected choices, the user gets 50% of max points
3.2. In addition to said 50% of the max points, first correct choice awards as much points needed so that each remaining correct choice awards a fraction of the total points equal to 1 over # of total choices up to max score possible.
3.3. Besides first correct choice, any other choice either awards or looses points equal to max points times 1 over # of total choices
3.4. For reference, try a 10 and 12 options example both with 4 correct choices in CodingRooms 
4. `Instant Feedback` -> `instantFeedback`
5. `Partial Credit` -> `partialCredit`
6. `Ignore Hide Grades` N/A. See Issue #134 discussion.
