### ISSUE TITLE
Should blink the cursor when waiting for input in the console

### ISSUE THREAD

**Issue by juicemind-dev** [JuiceMind/JuiceMind#194]
As you can see in the image below, the cursor is not blinking and just stays like this even though we are waiting for input.
<img width="450" alt="image" src="https://github.com/JuiceMind/JuiceMind/assets/170696439/9be2d3de-1b6f-4f68-80ee-fe74156e90ee">

**Comment by guido-ferraro** [comment]
https://github.com/user-attachments/assets/f33135c8-933a-42ef-a6b7-df20d5fb3274

This is an unrelated bug found while working on this. It was replicated without the changes from the PR relative to 194. The issue comes from loosing the reference from the user's input if the user types, then clicks outside, and then focus again on the Console tab and presses enter. This doesn't happen if the user adds the input and presses enter without leaving the Console tab.
