### ISSUE TITLE
README.md

### ISSUE THREAD

**Issue by mrlo-codes** [JuiceMind/JuiceMind#83]
Links to Issues and Features in README.md of repo are broken (they are default links to own repo)

Change links for Issues to https://github.com/JuiceMind/JuiceMind/issues
Do you plan to combine both features requests and issues into the issues tab? Or separate?

**Comment by juicemind-dev** [comment]
Thanks so much for pointing this out, I'm not too sure how we missed this. 

Yes, feature requests and issues are made in the issues tab (so they are technically created in the same place). I've merged it into one link on the README to avoid confusion (we've also fixed the link of course).

I will close this issue since it is a pretty simple one.
